### ISSUE TITLE
Branching and pull requests

### ISSUE THREAD

**Issue by owls-wonderland** [owls-wonderland/Graph-neural-networks-physics#1]
@jgamper I am not sure how to work with branching and pull requests. for example as right now we are writing ode together on Atom. do we need to create a seperate brunch when we upload it to github so you can check it before we upload it to master brunch?

**Comment by jgamper** [comment]
howdy!

short answer below :dagger: 

> do we need to create a seperate brunch when we upload it to github so you can check it before we upload it to master brunch?

Generally when you want to write add new feature, refactor code, or delete or change something in the code. You start with your master branch, then you create new branch that has name that is informative about the feature or bug that you are trying to address using this code you are about to write eg. "feature/kates_bubble_sort". Then you write that code in that branch, push to origin and create a pull request. THERE ARE FAR MORE DETAILS TO THIS, AND THEY WILL DEPEND ON WHAT THE COMMUNITY AROUND THAT REPOSITORY HAS AGREED TO BE THE STANDARD FOR PULL REQUESTS, ISSUES, FEATURES and CONTRIBUTIONS.

**Here is online tutorial that is specifically about branching**: https://learngitbranching.js.org/

Long answer below :firecracker: 

Since you are about to become a programming guru, some resources for you 

### MIT: The Missing Semester of Your CS Education 
Covers a wide range of Linux/UNIX basics. For example, using basic shell / command line commands to navigate and edit files. 

https://missing.csail.mit.edu/ 

Course Outline 
1/13: Course overview + the shell  
1/14: Shell Tools and Scripting  
1/15: Editors (Vim)  
1/16: Data Wrangling  
1/21: Command-line Environment  
1/22: Version Control (Git)  
1/23: Debugging and Profiling  
1/27: Metaprogramming  
1/28: Security and Cryptography  
1/29: Potpourri  
1/30: Q&A  

Resources 
Ubuntu Command Line for Beginners: https://ubuntu.com/tutorials/command-line-for-beginners#1-overview  
Digital Ocean*: https://www.digitalocean.com/community/tutorials/an-introduction-to-linux-basics  

*This covers navigating between file directories; viewing, creating and moving files; permissions basics; and using the manual pages for help. This guide is written for the use of Digital Ocean's 'droplet' service (a droplet is a virtual server) but is well written and a good introduction to basic commands. 

### Git 
Git.com has an excellent introduction 'book' online: 
https://git-scm.com/book/en/v2  

There is also a great online game to learn about git, specially branching. Highly recommended by John P. Even those familiar with git will find this useful. 
https://learngitbranching.js.org/  

### Using The Default Ubuntu Shell: Bash 
Resources 
Arch Wiki: https://wiki.archlinux.org/index.php/Bash  

 
### Users and Groups 
Resources 
Arch Wiki: https://wiki.archlinux.org/index.php/Users_and_groups  

###  Permissions (AKA Access Control) 
Linux has the concept of file/directory ownership and each file or directory always has one user as its owner and one group. Directories and files in Linux can also have three basic permissions: read, write, and execute. These are set independently for the file owner, the file group and all other users. 

Common Mistakes / "Gotchas" 
To be able to enter (cd into) a directory a user needs execute permission. People often think that read is required. 
To list (ls) file inside a directory the only read permission is required on the directory. Neither read or execute is required on the files themselves. However, this will only list the files and will not provide any access to metadata e.g. the file permissions for the listed files. For this, both the read and execute permissions on the directory are required. 

Resources 
Arch Wiki: https://wiki.archlinux.org/index.php/File_permissions_and_attributes  
Ryan's Tutorials: https://ryanstutorials.net/linuxtutorial/permissions.php  

### An Explanation of the Linux Standard(-ish) Directory Structure 
Linux comes in many varieties but most follow a common directory hierarchy. If you have ever wondered what the difference between /opt and /etc is then this is a good read: 
https://linuxhandbook.com/linux-directory-structure/  

![GetImageAttachment](https://user-images.githubusercontent.com/13080433/87572705-d99ba500-c6c3-11ea-9575-d59c5c20829e.png)

**Comment by jgamper** [comment]
### Linux 
Installing Software 
Most Linux distros come with a package manager to make installing, updating and removing software easy. For example, Ubuntu comes with apt. 
Apt (Ubuntu) 
https://help.ubuntu.com/lts/serverguide/apt.html  

Quickly Finding Files with locate 
https://linuxhandbook.com/locate-command/  

Searching Previously Typed Commands 
https://lifehacker.com/ctrl-r-to-search-and-other-terminal-history-tricks-278888  

### Background and History 
From UNIX to Ubuntu 
UNIX is an, originally proprietary, operating system created by Bell Labs (now AT&T) in the 1970s. There have since been many variants and derivatives, such as the Berkeley Software Distribution (BSD) released in 1977 and MINIX released in 1987. They all remain largely interoperable, often called 'UNIX-like' or 'POSIX-compliant', because of a set of 1988 standards called the Portable Operating System Interface (POSIX). 

UNIX has since had many proprietary and open-source descendants released such as OpenBSD and FreeBSD. Going even further down the family tree there is Darwin, the open-source core of macOS (and iOS etc.), which is based on FreeBSD. macOS, which is Darwin plus other software and frameworks, is officially 'Single UNIX Specification version 3' (UNIX 03) compliant, meaning that it meet a more stringent 2001 set of specifications than the original 1988 POSIX to be interoperable with UNIX. 

The Linux kernel was created in 1991 by Linus Torvalds as a free alternative to the proprietary UNIX-like operating system, MINIX.  Since the kernel itself performs only low-level operations such as interfacing with hardware, scheduling processes and managing memory, a set of applications known as the 'userland' were also required. Linus adopted the GNU set of tools for this. Hence what is commonly referred to as 'Linux' is really the Linux kernel with GNU tools (search the GNU/Linux naming controversy for more backstory).

Finally arriving at Ubuntu. Ubuntu is popular Linux distribution (the Linux kernel plus GNU tools and more) based on top of another popular Linux distribution, Debian. 

There are many complex off-shoots of the Linux project such as Android which is, similarly to macOS and UNIX, a mixture of an open-source modified Linux kernel and some basic userland software which is bundled with proprietary applications called Google Mobile Services. 

### The Linux Family Tree 

Linux versions are all related and form a kind of 'family tree'. For example, Debian Linux is the 'parent' of Ubuntu. Here is a (quite large) set of diagrams to help make sense of these relationships: 

https://distrowatch.com/dwres.php?resource=family-tree
